[window]
dimensions = { columns = 120, lines = 30 }
dynamic_padding = true
# MacOS
option_as_alt = "Both"

[font]
normal = { family = "VictorMono Nerd Font", style = "Regular" }
bold = { family = "VictorMono Nerd Font", style = "Bold" }
italic = { family = "VictorMono Nerd Font", style = "Italic" }
bold_italic = { family = "VictorMono Nerd Font", style = "Bold Italic" }
size = 15.0

[keyboard]
bindings = [
  # MacOS
  { key = "Tab", mods = "Control", action = "SelectNextTab" },
  { key = "Tab", mods = "Control|Shift", action = "SelectPreviousTab" },
]

[general]
import = ["colors.toml"]
